on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: macOS-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install librsvg (svg for pdf)
        run: brew install librsvg

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTex (pdf)
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install headless chromium (mmd -> img)
        run: quarto install chromium

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
